# Generated by Django 4.2.11 on 2024-04-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_color_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='time_untill',
            new_name='time_until',
        ),
    ]
