# Generated by Django 4.2.11 on 2024-04-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_time_untill_sale_time_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sale'),
        ),
    ]
