# Generated by Django 4.2.11 on 2024-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/'),
        ),
    ]
